modLoader="javafml"
loaderVersion="[${forge_version_major},)"
issueTrackerURL="https://github.com/${mod_github}/issues"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    # updateJSONURL="https://raw.githubusercontent.com/${mod_github}/master/update.json"
    displayURL="${mod_website}"
    logoFile="logo.png"
    # credits="I made this all myself"
    authors="${mod_author}"
    description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version_major},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"
